### ISSUE TITLE
Saving Models

### ISSUE THREAD

**Issue by lmangani** [repetere/ts-deeplearning#2]
Thanks for sharing your project! Having lots of fun with the examples (although I wish they worked without `import` in node) but having difficulties finding a clean way to save and reload generated models. Is there a native method and or a binding to use the tfjs save functions?

Thanks in advance!

**Comment by yawetse** [comment]
Hi @lmangani I plan on adding a wrapper around save and load models. If you want to take a quick stab at it, pull requests are welcomed!

**Comment by yawetse** [comment]
@lmangani the binding for tf save functions is on it's way! also you can import the built file using common js

**Comment by yawetse** [comment]
@lmangani e.g. requiring tenosrscript without using import
```javascript
const TS = require('tensorscript/bundle/tensorscript.cjs');
const MultipleLinearRegression = TS.MultipleLinearRegression;
const Model = new MultipleLinearRegression({ epoch:100, });
const inputData = [
  [ 0, 0, 0, 1, ],
  [ 0, 1, 0, 0, ],
  [ 0, 0, 0, 1, ]
]; 
const outputData = [
  [ 1, ],
  [ 0, ],
  [ 1, ]
];
const predictionData = [
  [ 0, 1, 0, 0 ],
  [ 0, 0, 0, 1 ],
];

Model.train(inputData,outputData)
  .then(() => Model.predict(predictionData,{probability: false}))
  .then(predictions => {
    console.log({ predictions }) //{ predictions: [ [ 0 ], [ 1 ] ] }
  })
  .catch(err=>console.error(err));
 ```

**Comment by yawetse** [comment]
@lmangani saving and loading models are finally incorporated

you can see the test (https://github.com/repetere/tensorscript/blob/master/test/unit/model_interface_spec.js) as an example or below

### loading a model
```javascript
      const loadedModelPath = `file://path/to/some/model.json`;
      const trainedModelToLoad = new MultipleLinearRegression({ });
      await trainedModelToLoad.loadModel(loadedModelPath);
      const loaded_predictions = await trainedModelToLoad.predict(input_x_matrix);
```

### saving a model
```javascript
      const saveModelPath = `file://path/to/some/model_directory`;
      const MLRModel = new MultipleLinearRegression({  fit: {  epochs: 100,  batchSize: 5,  },  });
      await MLRModel.train(x_matrix, y_matrix);
      const savedModelStatus = await trainedMLR.saveModel(saveModelPath);
```
